### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by Connum** [stephensolis/ustvnow-client#1] opened 2017-04-29 07:21 UTC
Getting a 403 status when retrieving channel playlist URL. Any chance of fixing this?

**Comment by stephensolis** [comment] 2017-04-29 13:48
This can happen if you don't activate your USTVnow account. Did you click the link in the email when signing up?

**Comment by Connum** [comment] 2017-04-29 18:44
Hi there,

the account is definitely activated, and I can watch the channels fine via the web interface (also the mobile version that the script is using). I have a free account if that should matter.

Any help appreciated!

**Comment by stephensolis** [comment] 2017-04-29 18:58
Hmm, that's strange.
Can you post the command you ran and the output of the program? (Please edit out your token though!)

**Comment by Connum** [comment] 2017-04-30 10:43
This is what I get in the console, all login and session data replaced with *****

> python ustvnow.py -u ***** -p ***** -c wgal -q highest
[+] Logging in... done.
[+] Retrieving channel list... done.
[*] Got 7 available channels (32 total).
[+] Retrieving channel playlist URL... failed.
[!] Error: 403 Client Error: Forbidden for url: https://m.ustvnow.com/stream/1/live/view?token=*****&scode=wgal.
[*] Sent request:
      GET https://m.ustvnow.com/stream/1/live/view?token=*****&scode=wgal
      User-Agent: python-requests/2.13.0
      Accept-Encoding: gzip, deflate
      Accept: */*
      Connection: keep-alive
[*] Received response:
      403 Forbidden
      Cache-Control: no-cache, no-store, max-age=0, must-revalidate
      Content-Type: text/html; charset=UTF-8
      Date: Sun, 30 Apr 2017 10:41:00 GMT
      Expires: Fri, 01 Jan 2010 00:00:00 GMT
      Pragma: no-cache
      Server: IBM WebSphere
      Set-Cookie: JSESSIONID=*****; path=/
      X-Debug-user-notallowed: *****
      Content-Length: 0

**Comment by stephensolis** [comment] 2017-05-01 17:27
This is very strange, I can't reproduce the error at all with my own free account using the exact same command...

Just out of curiosity, if you make a new account ([here](https://watch.ustvnow.com/subscription/free-channels)), do you still get the same error?

**Comment by Connum** [comment] 2017-05-17 17:13
Sorry for not getting back. It actually works with a newly created account! Very strange...

**Comment by stephensolis** [comment] 2017-05-17 18:52
That's very strange... Thanks for letting me know!

I'm going to close this then, since it looks like it's an issue on USTVnow's end.

**Closed by stephensolis** 2017-05-17 18:52 UTC

**Comment by Connum** [comment] 2017-09-20 14:15
A quick followup on this: It has stopped working with that new account as well after the trial period, so I guess that was the problem with the first account as well. So it seems this does only work with active trial and fully payed accounts.

I assume this is because outside the trial you can only use the browser for accessing the low-quality streams, but no longer the mobile version, which is the base for this tool. If you don't see any possibility around this, it seems there's no other choice than creating a new trial account every time your old one expires, or a payed account.
